#%RAML 1.0 NamedExample
value:

  imeZ: Sara
  przZ: Stankov
  telZ: '0637794600'
  adresaZ: Cirila i Metodija 13
  emailZ: sarass94@gmail.com
  username: stankovsara94
  password: '12345'
  plata: 60000
  zaposlenOd: 2020-03-03
  zaposlenDo: 2020-04-04
  radi: false
  idUloge: 2