#%RAML 1.0 NamedExample

value:
  -
   idPlacanja: 1
   datumIVremeUplate: 2020-04-14T10:00:00
   ukupnaCena: 220
   tipPlacanja: Kes
   idKupca: 6
   idPorudzbine: 6
  -
   idPlacanja: 2
   datumIVremeUplate: 2020-04-15T12:00:00
   ukupnaCena: 220
   tipPlacanja: Kes
   idKupca: 8
   idPorudzbine: 9
  