#%RAML 1.0 NamedExample
value:
  -
   idRejtinga: 2
   vremeIDatumR: 2020-04-15T16:00:00
   naslov: Odlicno!
   recenzija: Nikada nisam jeo bolje
   brZvezdica: '5'
   idporudzbine: 2  
  -
   idRejtinga: 3
   vremeIDatumR: 2020-04-15T16:00:00
   naslov: Odusevljena sam!
   recenzija: Prvi put sam porucivala, ali definitivno ne i poslednji.
   brZvezdica: '5'
   idporudzbine: 3  
  