#%RAML 1.0 NamedExample
value:

  -
    idStavkeMenija: 1
    nazivSM: Cedevita
    opisSM: U ponudi su limun, narandza, zova
    cenaSM: 120
    kalorijeSM: 87
    kategorija: Bezalkoholno pice
    idMenija: 2
  -

    idStavkeMenija: 2
    nazivSM: Gusti sok
    opisSM: Breskva
    cenaSM: 120
    kalorijeSM: 97
    kategorija: Bezalkoholno pice
    idMenija: 2
  